"use client";

import { useActionState } from "react";
import {
  acceptSuggestionAction,
  ignoreSuggestionAction,
  type ActionState,
} from "@/app/(admin)/admin/(console)/requests/actions";
import { TYPE_LABELS } from "@/domain/feedback";
import type { FeedbackTypeName } from "@/domain/config";
import { Button } from "@/components/ui/button";

const initial: ActionState = { error: null };

const TYPES = new Set<string>(["idea", "problem", "improvement", "bug", "other"]);

export function SuggestionPanel({
  feedbackId,
  suggestion,
}: {
  feedbackId: string;
  suggestion: {
    status: "pending" | "ignored" | "linked";
    suggestedType: string | null;
    topics: string[];
    similarity: number | null;
    model: string;
    request: { id: string; title: string; visibility: string } | null;
  };
}) {
  const [linkState, linkAction, linkPending] = useActionState(acceptSuggestionAction, initial);
  const [ignoreState, ignoreAction, ignorePending] = useActionState(ignoreSuggestionAction, initial);
  const typeLabel =
    suggestion.suggestedType && TYPES.has(suggestion.suggestedType)
      ? TYPE_LABELS[suggestion.suggestedType as FeedbackTypeName]
      : null;
  const canAct = suggestion.status === "pending";

  return (
    <section data-suggestion className="mb-6 space-y-3 rounded-md border border-border p-3">
      <div>
        <h3 className="text-sm font-medium">Generated suggestion</h3>
        <p className="mt-1 text-xs text-muted-foreground">Generated by {suggestion.model}. The original message is unchanged.</p>
      </div>
      {typeLabel ? <p className="text-sm">Type: {typeLabel}</p> : null}
      <p className="text-sm">
        Topics: {suggestion.topics.length > 0 ? suggestion.topics.join(", ") : "None"}
      </p>
      {suggestion.request && suggestion.similarity !== null ? (
        <p className="text-sm">
          {suggestion.request.title}
          <span className="mt-1 block text-xs text-muted-foreground">
            Similarity {suggestion.similarity} · {suggestion.request.visibility}
          </span>
        </p>
      ) : (
        <p className="text-sm text-muted-foreground">No existing request matched.</p>
      )}
      {suggestion.status === "ignored" ? (
        <p className="text-sm text-muted-foreground">Ignored. This feedback stays unlinked.</p>
      ) : null}
      {canAct ? (
        <div className="flex flex-wrap gap-2">
          {suggestion.request && suggestion.similarity !== null ? (
            <form action={linkAction}>
              <input type="hidden" name="feedbackId" value={feedbackId} />
              {linkState.error ? <p className="mb-2 text-sm text-destructive" role="alert">{linkState.error}</p> : null}
              <Button type="submit" disabled={linkPending}>{linkPending ? "Linking…" : "Link"}</Button>
            </form>
          ) : null}
          <form action={ignoreAction}>
            <input type="hidden" name="feedbackId" value={feedbackId} />
            {ignoreState.error ? <p className="mb-2 text-sm text-destructive" role="alert">{ignoreState.error}</p> : null}
            <Button type="submit" variant="outline" disabled={ignorePending}>
              {ignorePending ? "Ignoring…" : "Ignore"}
            </Button>
          </form>
        </div>
      ) : null}
    </section>
  );
}
